### ISSUE TITLE
Summaries broken on dev site

### ISSUE THREAD

**Issue by bmbouter** [pulp/analytics.pulpproject.org#30]
On Oct 20th we merged https://github.com/pulp/analytics.pulpproject.org/pull/23 to the dev site. It has not been released to production.

Here is the info of the DailySummary entries:
* Oct 19th - typical and does not contain an `ageCount` entry
* Oct 20th - typical and does contain an `ageCount` entry (see example below)
* Oct 21st and newer - The `DailySummary` is created but the value is `{}` which is totally broken.

```
"ageCount": [{
		"age": 0,
		"count": 100
	}, {
		"age": 14,
		"count": 4
	}, {
		"age": 7,
		"count": 1
	}, {
		"age": 1,
		"count": 2
	}, {
		"age": 2,
		"count": 1
	}, {
		"age": 9,
		"count": 1
	}]
```

**Comment by bmbouter** [comment]
Here's a dump of the dev site's database with a zip file containing the .json data.

[dev-site.zip](https://github.com/pulp/analytics.pulpproject.org/files/9862013/dev-site.zip)

**Comment by mdellweg** [comment]
From my dev env: `pulpcore.app.tasks.telemetry:WARNING: Sending telemetry failed with statuscode 500 from https://dev.analytics.pulpproject.org/`

**Comment by bmbouter** [comment]
I had two thoughts I wanted to share:
1) I (randomly while not thinking about it) remembered that these openshift environments are actually on Python 2.7. Perhaps that's why you can't reproduce it.
2) I think your 500 error submitting dev telemetry is another indicator of the apps brokenness.

**Comment by bmbouter** [comment]
@mdellweg and I fixed this this morning.

## What happened?

The actual root cause was seemingly a bad deployment of this commit on openshift. The database had been migrated, but the code had not been. We no longer have the event logs from the bad deployment. I remember logging in and seeing that the app had "failed health checks". Why it had failed health checks, I don't know, but I believe openshift rolled back the application after enough time of a bad failed health check. The issue is, it never rolled back the db...

## What fixed it?

Deploying another [unrelated PR](https://github.com/pulp/analytics.pulpproject.org/pull/31) got it working again.

## Why summarization also stopped working?

The short answer is: it actually was working, but there was no system data to summarize. While the DB was too new for the code telemetry could not be accepted due to the old code not saving the first_seen database value which the DB rejected. This caused a gap in all incoming telemetry for about 5 days. During that 5 day gap, summarization happened but produced `{}` entries which is what you get when there is no system data to summarize.

**Comment by bmbouter** [comment]
In deploying to production the readiness probe failed I believe for the same reason:

```
Internal Server Error: /
Traceback (most recent call last):
  File "/opt/app-root/lib64/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/opt/app-root/lib64/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/app-root/lib64/python3.9/site-packages/django/views/generic/base.py", line 84, in view
    return self.dispatch(request, *args, **kwargs)
  File "/opt/app-root/lib64/python3.9/site-packages/django/utils/decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
  File "/opt/app-root/lib64/python3.9/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/opt/app-root/lib64/python3.9/site-packages/django/views/generic/base.py", line 119, in dispatch
    return handler(request, *args, **kwargs)
  File "/srv/app/pulpanalytics/views.py", line 230, in get
    self._label_xy_versions_data_for_plugin(context, "age_count", fill=True)
  File "/srv/app/pulpanalytics/views.py", line 150, in _label_xy_versions_data_for_plugin
    new_data[0]["fill"] = True
IndexError: list index out of range
```
