### ISSUE TITLE
Proposal: Collect whether installations have customized access polilcies

### ISSUE THREAD

**Issue by mdellweg** [pulp/analytics.pulpproject.org#84]
## What question will this help us answer?
Is carrying the access policy around in the database for users to edit a used feature?
Do people use Pulp in a multi use / domain framework?
How much do people customize their RBAC system?

## What is a specific example of the data to be gathered?
```yaml
rbac_stats:
  users: 42
  groups: 12
  domains: 3
  customized_roles: 18
  customized_access_policies: 5
```

## How will this metric be stored in the database or gathered at runtime?
Gathered at runtime.

## Will the gathering and/or storage of this cause unacceptable burden/load on Pulp?
Just a fixed number of database calls, `O(1)`. No permanent storage.

## Is this metric Personally-Identifiable-Data?
Data is anonymous, but can still be uniquely identifiable [If your installation is the only one with 23 customized policies.].
As anonymous as pure numbers.

## What pulpcore version will this be collected with?
`>= 3.23`

## Summarization
Collect number of systems with certain number of [items].

## Visualization
Stacked graphs (5).

**Comment by mdellweg** [comment]
While we are at it, let's reserve a field for the number of domains in the system.

**Comment by bmbouter** [comment]
Technically, domains is distinct from RBAC, can the domain number be moved outside of the RBAC data structure.

Also:
* what does the domains number report if domains is disabled?
* what does the domains number report if it's enabled but only the default domain is used?

**Comment by mdellweg** [comment]
We should distiguish systems with one and switched off domains.

**Comment by ggainey** [comment]
> Technically, domains is distinct from RBAC, can the domain number be moved outside of the RBAC data structure.

Discussion: people are receptive to either "in" rbac stanza (since domains require rbac) or as it's own thing

> * what does the domains number report if domains is disabled?

Discussion: return 0 if disabled. Or, make it not-returned?

> * what does the domains number report if it's enabled but only the default domain is used?

Discussion: returns "1"

**Comment by bmbouter** [comment]
This is expected to generate 5 new graphs.
